#=============================================================================
# Project settings
#=============================================================================
# Only build master and develop on push; do not build every branch.
branches:
  only:
    - master



#=============================================================================
# Builds
#=============================================================================
jobs:
  include:
    - python: '3.7'
      os: linux
      language: python

# Need dot to build
addons:
  apt:
    packages:
      - graphviz

# Install various dependencies
install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements.txt


script:
  - make clean --silent
  - make SPHINXOPTS=-W
