name: ci
on:
  push:
    branches:
      - main
    tags:
      - '*'

  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      container: ${{ steps.filter.outputs.container }}
      outputs: ${{ steps.filter.outputs.outputs }}
      style: ${{ steps.filter.outputs.style }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        if: ${{ github.event_name == 'push' }}
        with:
          fetch-depth: 0

        # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d  # v4.0.1
        id: filter
        with:
          filters: |
            container:
              - '.github/**'
              - 'container/**'
            style:
              - '*.rst'
            outputs:
              - '.github/**'
              - 'container/**'
              - 'outputs/**.sh'

  container:
    if: ${{ needs.changes.outputs.container == 'true' || startsWith(github.ref, 'refs/tags/') }}
    needs: changes
    uses: ./.github/workflows/container.yml

  outputs:
    if: |
      !cancelled()
      && contains(needs.*.result, 'success')
      && !contains(needs.*.result, 'failure')
      && (needs.changes.outputs.outputs == 'true'
      || startsWith(github.ref, 'refs/tags/'))
    needs: [ changes, container ]
    uses: ./.github/workflows/outputs.yml
    with:
      with_pr_container: ${{ needs.container.result == 'success' }}

  style:
    if: ${{ needs.changes.outputs.style == 'true' }}
    needs: changes
    uses: ./.github/workflows/style.yml
