name: Generate outputs
on:
  workflow_call:
    inputs:
      with_pr_container:
        required: true
        type: boolean

jobs:
  re-generate:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout (Push)
      if: github.event_name != 'pull_request'
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        ref: ${{ github.head_ref }}

    - name: Checkout (PR)
      if: github.event_name == 'pull_request'
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Download container from artifact if PR
      if: github.event_name == 'pull_request' && inputs.with_pr_container
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
      with:
        name: tutorial-container
        path: /tmp

    - name: Import container from PR artifact
      if: github.event_name == 'pull_request' && inputs.with_pr_container
      run: |
        docker load --input /tmp/tutorial-container.tar
        docker image ls -a

    - name: Re-generate outputs from tutorial scripts
      run: |
        chmod -R a+w outputs
        mkdir spack-home && sudo chmod -R a+rwx spack-home
        DOCKER_RUN_OPTS="-e COLUMNS=94 -e COLIFY_SIZE=24x94 -v $(pwd)/spack-home:/home/spack"
        make -C outputs -j $(nproc) DOCKER_RUN_OPTS="$DOCKER_RUN_OPTS" container=ghcr.io/spack/tutorial

    - name: Show diff of modified files
      run: |
        git diff HEAD outputs/

    - name: Upload outputs as artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: generated-outputs
        path: outputs/
        retention-days: 7
        compression-level: 9
