name: Generate outputs

on: workflow_dispatch

jobs:
  generate-outputs:
    runs-on: ubuntu-latest
    name: Generate ouputs
    steps:
    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

    - name: Run
      run: |
        chmod -R a+w outputs
        make -C outputs -j $(nproc) DOCKER_RUN_OPTS="-e COLUMNS=94 -e LINES=24"

    - name: Create pull request
      run: gh pr create -B main -H regenerate-outputs --title "Regenerate outputs" --body "Automated update"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
